# Generated by Django 6.0.5 on 2026-05-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_college_seed_data_and_profile_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationHeaderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('aishe_code', models.CharField(max_length=30)),
                ('head_name', models.CharField(max_length=255)),
                ('head_contact', models.CharField(max_length=255)),
                ('hei_address', models.TextField()),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination_header_submission', to='core.collegeprofile')),
            ],
        ),
    ]
