# Generated by Django 6.0.5 on 2026-05-21 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nominationheadersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='form_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
