# Generated by Django 6.0.5 on 2026-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nominationheadersubmission_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='accreditation_status',
            field=models.CharField(default='not_accredited', max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='affiliating_university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='institution_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='naac_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='naac_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='nodal_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='nodal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='nodal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='total_faculty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='total_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='ugc_status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheadersubmission',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
