# Generated by Django 6.0.5 on 2026-05-24 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('aishe_code', models.CharField(max_length=50)),
                ('head_name', models.CharField(max_length=255)),
                ('head_contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('hei_address', models.TextField()),
                ('hei_type', models.CharField(choices=[('university', 'University'), ('college', 'College')], max_length=20)),
                ('academic_session', models.CharField(default='2024-25', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination_header', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
