# Generated by Django 6.0.5 on 2026-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationheader',
            name='hei_type',
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='accreditation_status',
            field=models.CharField(default='not_accredited', max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='affiliating_university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='establishment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='institution_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='institution_type',
            field=models.CharField(default='college', max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='naac_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='naac_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='nodal_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='nodal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='nodal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='total_faculty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='total_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='ugc_status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='nominationheader',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='nominationheader',
            name='head_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nominationheader',
            name='hei_address',
            field=models.TextField(blank=True),
        ),
    ]
