# Generated by Django 6.0.5 on 2026-05-24 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_nominationheader_hei_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationheader',
            name='form_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
