# Generated by Django 6.0.5 on 2026-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_nominationheader_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationheader',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
